// Generated by tools/prepare-uniforms.py from the design art. Do not edit by hand.
// Colors are sampled from the art so the 3D materials match the artwork.
export const ART = {
 "helmet": {
  "helmet-red": {
   "shell": "#C9001F",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-red",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-white": {
   "shell": "#FFFFFF",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-white",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-white-louie": {
   "shell": "#FFFFFF",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-white-louie",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-black": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-black",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-white-20": {
   "shell": "#FFFFFF",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-white-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-red-20": {
   "shell": "#C9001F",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-red-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-black-20": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-black-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-whitealt-20": {
   "shell": "#FFFFFF",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-whitealt-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-script": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": false,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-script",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-redscript": {
   "shell": "#C9001F",
   "finish": "gloss",
   "mirror": false,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-redscript",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-whitestripe": {
   "shell": "#FFFFFF",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [
    {
     "at": 0,
     "w": 0.06,
     "color": "#C9001F"
    }
   ],
   "decal": "decal-helmet-whitestripe",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-halloween": {
   "shell": "#000000",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-halloween",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-redgold": {
   "shell": "#C9001F",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-redgold",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackchrome": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 1,
   "stripe": [],
   "decal": "decal-helmet-blackchrome",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackmatte": {
   "shell": "#000000",
   "finish": "matte",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-blackmatte",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackstripe": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [
    {
     "at": -0.026,
     "w": 0.012,
     "color": "#FFFFFF"
    },
    {
     "at": 0,
     "w": 0.04,
     "color": "#C9001F"
    },
    {
     "at": 0.026,
     "w": 0.012,
     "color": "#FFFFFF"
    }
   ],
   "decal": "decal-helmet-blackstripe",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-black23": {
   "shell": "#000000",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-black23",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackmattechrome": {
   "shell": "#000000",
   "finish": "matte",
   "mirror": true,
   "decalMetal": 1,
   "stripe": [],
   "decal": "decal-helmet-blackmattechrome",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  }
 },
 "jersey": {
  "jersey-red": {
   "base": "#C9001F",
   "trim": "#000000",
   "number": {
    "box": [
     458,
     642,
     916,
     1150
    ],
    "fill": "#FFFFFF",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-white": {
   "base": "#FFFFFF",
   "trim": "#000000",
   "number": {
    "box": [
     453,
     642,
     912,
     1150
    ],
    "fill": "#C9001F",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black": {
   "base": "#000000",
   "trim": "#000000",
   "number": {
    "box": [
     433,
     586,
     939,
     1069
    ],
    "fill": "#FFFFFF",
    "outline": "#C9001F"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-red-wing": {
   "base": "#C9001F",
   "trim": "#C9001F",
   "number": {
    "box": [
     462,
     642,
     939,
     1168
    ],
    "fill": "#FFFFFF",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-white-wing": {
   "base": "#FFFFFF",
   "trim": "#8A8D8F",
   "number": {
    "box": [
     461,
     642,
     939,
     1169
    ],
    "fill": "#C9001F",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black-wing": {
   "base": "#000000",
   "trim": "#8A8D8F",
   "number": {
    "box": [
     479,
     647,
     939,
     1168
    ],
    "fill": "#FFFFFF",
    "outline": "#C9001F"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-red-20": {
   "base": "#C9001F",
   "trim": "#C9001F",
   "number": {
    "box": [
     497,
     582,
     922,
     1056
    ],
    "fill": "#FFFFFF",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-white-20": {
   "base": "#FFFFFF",
   "trim": "#000000",
   "number": {
    "box": [
     495,
     583,
     923,
     1055
    ],
    "fill": "#C9001F",
    "outline": "#C9001F"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black-20": {
   "base": "#000000",
   "trim": "#8A8D8F",
   "number": {
    "box": [
     497,
     581,
     923,
     1054
    ],
    "fill": "#FFFFFF",
    "outline": "#C9001F"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-whitealt-20": {
   "base": "#FFFFFF",
   "trim": "#000000",
   "number": {
    "box": [
     495,
     583,
     923,
     1055
    ],
    "fill": "#000000",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-halloween": {
   "base": "#000000",
   "trim": "#000000",
   "number": {
    "box": [
     433,
     586,
     939,
     1069
    ],
    "fill": "#e8e8c8",
    "outline": "#b88838"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-ironwings": {
   "base": "#8A8D8F",
   "trim": "#FFFFFF",
   "number": {
    "box": [
     462,
     642,
     938,
     1168
    ],
    "fill": "#FFFFFF",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-redgold": {
   "base": "#C9001F",
   "trim": "#000000",
   "number": {
    "box": [
     458,
     642,
     916,
     1150
    ],
    "fill": "#c8a848",
    "outline": "#000000"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black-23": {
   "base": "#000000",
   "trim": "#8A8D8F",
   "number": {
    "box": [
     479,
     647,
     940,
     1169
    ],
    "fill": "#FFFFFF",
    "outline": "#8A8D8F"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  }
 },
 "pants": {
  "pants-red": {
   "base": "#C9001F",
   "socks": "#C9001F",
   "bands": [
    {
     "at": 0.0107,
     "w": 0.0329,
     "color": "#FFFFFF"
    },
    {
     "at": -0.0105,
     "w": 0.0094,
     "color": "#000000"
    }
   ],
   "bandEnd": 1.0,
   "logos": "logos-pants-red",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-white": {
   "base": "#FFFFFF",
   "socks": "#FFFFFF",
   "bands": [
    {
     "at": 0.0107,
     "w": 0.0567,
     "color": "#000000"
    },
    {
     "at": 0.0107,
     "w": 0.0447,
     "color": "#C9001F"
    }
   ],
   "bandEnd": 1.0,
   "logos": "logos-pants-white",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [
    {
     "at": 0.0107,
     "w": 0.0447,
     "color": "#C9001F"
    },
    {
     "at": -0.0164,
     "w": 0.0094,
     "color": "#FFFFFF"
    }
   ],
   "bandEnd": 1.0,
   "logos": "logos-pants-black",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-red-script": {
   "base": "#C9001F",
   "socks": "#C9001F",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-red-script",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-white-script": {
   "base": "#FFFFFF",
   "socks": "#FFFFFF",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-white-script",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black-script": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-black-script",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-red-20": {
   "base": "#C9001F",
   "socks": "#C9001F",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-red-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-white-20": {
   "base": "#FFFFFF",
   "socks": "#FFFFFF",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-white-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black-20": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-black-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-whitealt-20": {
   "base": "#FFFFFF",
   "socks": "#FFFFFF",
   "bands": [
    {
     "at": 0.0078,
     "w": 0.0459,
     "color": "#000000"
    },
    {
     "at": -0.0169,
     "w": 0.0035,
     "color": "#000000"
    }
   ],
   "bandEnd": 1.0,
   "logos": "logos-pants-whitealt-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-halloween": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [
    {
     "at": -0.0116,
     "w": 0.0106,
     "color": "#b08d3e"
    },
    {
     "at": 0.0095,
     "w": 0.0106,
     "color": "#b08d3e"
    },
    {
     "at": 0.0307,
     "w": 0.0106,
     "color": "#b08d3e"
    }
   ],
   "bandEnd": 1.0,
   "logos": "logos-pants-halloween",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-ironwings": {
   "base": "#8A8D8F",
   "socks": "#8A8D8F",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-ironwings",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-redgold": {
   "base": "#C9001F",
   "socks": "#C9001F",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-redgold",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black-23": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-black-23",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  }
 },
 "socks": {
  "socks-red": "#C9001F",
  "socks-white": "#FFFFFF",
  "socks-black": "#000000",
  "socks-gray": "#8A8D8F",
  "socks-red-20": "#C9001F",
  "socks-white-20": "#FFFFFF",
  "socks-black-20": "#000000",
  "socks-gray-20": "#8A8D8F"
 },
 "shoes": {
  "shoes-black": "#000000",
  "shoes-white": "#FFFFFF",
  "shoes-red": "#C9001F",
  "shoes-gray": "#8A8D8F"
 }
};
