// Generated by tools/prepare-uniforms.py from the design art. Do not edit by hand.
// Colors are sampled from the art so the 3D materials match the artwork.
export const ART = {
 "helmet": {
  "helmet-red": {
   "shell": "#c9001f",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-red",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-white": {
   "shell": "#ffffff",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-white",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-white-louie": {
   "shell": "#ffffff",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-white-louie",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-black": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-black",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-white-20": {
   "shell": "#ffffff",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-white-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-red-20": {
   "shell": "#a2032c",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-red-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-black-20": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-black-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-whitealt-20": {
   "shell": "#f0f0f0",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-whitealt-20",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-script": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": false,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-script",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-redscript": {
   "shell": "#c9001f",
   "finish": "gloss",
   "mirror": false,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-redscript",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-whitestripe": {
   "shell": "#ffffff",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [
    {
     "at": 0,
     "w": 0.06,
     "color": "#c8102e"
    }
   ],
   "decal": "decal-helmet-whitestripe",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-halloween": {
   "shell": "#0f0f0f",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-halloween",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-redgold": {
   "shell": "#c9001f",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-redgold",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackchrome": {
   "shell": "#141416",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 1,
   "stripe": [],
   "decal": "decal-helmet-blackchrome",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackmatte": {
   "shell": "#343437",
   "finish": "matte",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-blackmatte",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackstripe": {
   "shell": "#000000",
   "finish": "gloss",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [
    {
     "at": -0.026,
     "w": 0.012,
     "color": "#ffffff"
    },
    {
     "at": 0,
     "w": 0.04,
     "color": "#c8102e"
    },
    {
     "at": 0.026,
     "w": 0.012,
     "color": "#ffffff"
    }
   ],
   "decal": "decal-helmet-blackstripe",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-black23": {
   "shell": "#1e1e20",
   "finish": "satin",
   "mirror": true,
   "decalMetal": 0,
   "stripe": [],
   "decal": "decal-helmet-black23",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  },
  "helmet-blackmattechrome": {
   "shell": "#2e2e31",
   "finish": "matte",
   "mirror": true,
   "decalMetal": 1,
   "stripe": [],
   "decal": "decal-helmet-blackmattechrome",
   "decalArt": {
    "width": 752,
    "height": 762,
    "frontX": 85,
    "topY": 5,
    "pxPerUnit": 541.7
   }
  }
 },
 "jersey": {
  "jersey-red": {
   "base": "#c9001f",
   "trim": "#000000",
   "number": {
    "box": [
     458,
     642,
     916,
     1150
    ],
    "fill": "#f8f8f8",
    "outline": "#080808"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-white": {
   "base": "#ffffff",
   "trim": "#000000",
   "number": {
    "box": [
     453,
     642,
     912,
     1150
    ],
    "fill": "#c80818",
    "outline": "#080808"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black": {
   "base": "#000000",
   "trim": "#4d4d4d",
   "number": {
    "box": [
     433,
     586,
     939,
     1069
    ],
    "fill": "#f8f8f8",
    "outline": "#c80818"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-red-wing": {
   "base": "#c9001f",
   "trim": "#ff5050",
   "number": {
    "box": [
     462,
     642,
     939,
     1168
    ],
    "fill": "#f8f8f8",
    "outline": "#080808"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-white-wing": {
   "base": "#ffffff",
   "trim": "#999999",
   "number": {
    "box": [
     461,
     642,
     939,
     1169
    ],
    "fill": "#c80818",
    "outline": "#080808"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black-wing": {
   "base": "#000000",
   "trim": "#666666",
   "number": {
    "box": [
     479,
     647,
     939,
     1168
    ],
    "fill": "#f8f8f8",
    "outline": "#c80818"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-red-20": {
   "base": "#c2002c",
   "trim": "#750c28",
   "number": {
    "box": [
     497,
     582,
     922,
     1056
    ],
    "fill": "#f8f8f8",
    "outline": "#281818"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-white-20": {
   "base": "#ffffff",
   "trim": "#0a0a0a",
   "number": {
    "box": [
     495,
     583,
     923,
     1055
    ],
    "fill": "#c80828",
    "outline": "#b80828"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black-20": {
   "base": "#000000",
   "trim": "#959595",
   "number": {
    "box": [
     497,
     581,
     923,
     1054
    ],
    "fill": "#f8f8f8",
    "outline": "#b80828"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-whitealt-20": {
   "base": "#ffffff",
   "trim": "#242122",
   "number": {
    "box": [
     495,
     583,
     923,
     1055
    ],
    "fill": "#181818",
    "outline": "#181808"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-halloween": {
   "base": "#000000",
   "trim": "#4d4d4d",
   "number": {
    "box": [
     433,
     586,
     939,
     1069
    ],
    "fill": "#e8e8c8",
    "outline": "#b88838"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-ironwings": {
   "base": "#8f9195",
   "trim": "#e1e2e4",
   "number": {
    "box": [
     462,
     642,
     938,
     1168
    ],
    "fill": "#f8f8f8",
    "outline": "#080808"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-redgold": {
   "base": "#c9001f",
   "trim": "#000000",
   "number": {
    "box": [
     458,
     642,
     916,
     1150
    ],
    "fill": "#c8a848",
    "outline": "#080808"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  },
  "jersey-black-23": {
   "base": "#000000",
   "trim": "#666666",
   "number": {
    "box": [
     479,
     647,
     940,
     1169
    ],
    "fill": "#d8d8d8",
    "outline": "#889898"
   },
   "art": {
    "width": 1366,
    "height": 1408
   }
  }
 },
 "pants": {
  "pants-red": {
   "base": "#c9001f",
   "socks": "#c9001f",
   "bands": [
    {
     "at": 0.0107,
     "w": 0.0329,
     "color": "#ffffff"
    },
    {
     "at": -0.0105,
     "w": 0.0094,
     "color": "#111113"
    }
   ],
   "bandEnd": 0.92,
   "logos": "logos-pants-red",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-white": {
   "base": "#ffffff",
   "socks": "#ffffff",
   "bands": [
    {
     "at": 0.0107,
     "w": 0.0447,
     "color": "#c9001f"
    },
    {
     "at": -0.0164,
     "w": 0.0094,
     "color": "#111113"
    }
   ],
   "bandEnd": 0.92,
   "logos": "logos-pants-white",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [
    {
     "at": 0.0107,
     "w": 0.0447,
     "color": "#c9001f"
    },
    {
     "at": -0.0164,
     "w": 0.0094,
     "color": "#f2f2f0"
    }
   ],
   "bandEnd": 0.92,
   "logos": "logos-pants-black",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-red-script": {
   "base": "#c9001f",
   "socks": "#c9001f",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-red-script",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-white-script": {
   "base": "#ffffff",
   "socks": "#ffffff",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-white-script",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black-script": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-black-script",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-red-20": {
   "base": "#c2002c",
   "socks": "#c2002c",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-red-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-white-20": {
   "base": "#ffffff",
   "socks": "#ffffff",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-white-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black-20": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-black-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-whitealt-20": {
   "base": "#ffffff",
   "socks": "#ffffff",
   "bands": [
    {
     "at": 0.0078,
     "w": 0.0459,
     "color": "#161412"
    },
    {
     "at": -0.0169,
     "w": 0.0035,
     "color": "#464442"
    }
   ],
   "bandEnd": 1.0,
   "logos": "logos-pants-whitealt-20",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-halloween": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [
    {
     "at": -0.0116,
     "w": 0.0106,
     "color": "#b08d3e"
    },
    {
     "at": 0.0095,
     "w": 0.0106,
     "color": "#b08d3e"
    },
    {
     "at": 0.0307,
     "w": 0.0106,
     "color": "#b08d3e"
    }
   ],
   "bandEnd": 1.0,
   "logos": "logos-pants-halloween",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-ironwings": {
   "base": "#8f9195",
   "socks": "#8f9195",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-ironwings",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-redgold": {
   "base": "#c9001f",
   "socks": "#c9001f",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-redgold",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  },
  "pants-black-23": {
   "base": "#000000",
   "socks": "#000000",
   "bands": [],
   "bandEnd": 1.0,
   "logos": "logos-pants-black-23",
   "logoArt": {
    "width": 1084,
    "height": 600
   }
  }
 },
 "socks": {
  "socks-red": "#c8102e",
  "socks-white": "#ffffff",
  "socks-black": "#0a0a0a",
  "socks-gray": "#8f9195",
  "socks-red-20": "#c8102e",
  "socks-white-20": "#ffffff",
  "socks-black-20": "#0a0a0a",
  "socks-gray-20": "#8f9195"
 },
 "shoes": {
  "shoes-black": "#181819",
  "shoes-white": "#dddddf",
  "shoes-red": "#a81d3a",
  "shoes-gray": "#545559"
 }
};
